server:
  port: ${SERVER_PORT:9000}

spring:

  application:
    name: agrotis

  profiles:
    active: default

---
spring:
  config:
    activate:
      on-profile: default

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:challenge_user}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
        format_sql: true
        use_sql_comments: true
        connection:
          isolation: 2
        cache:
          use_second_level_cache: false
          use_query_cache: false
        type:
          enumType:
            type: pgsql_enum
        jdbc:
          log:
            non_contextual_creation: true
    open-in-view: false
    show-sql: true

  sql:
    init:
      mode: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
